### ISSUE TITLE
Dashboard's "Delete Domain" function doesn't work

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/Iamus#25]
My https://dashboard.vircadia.com/domain page is showing a bunch of "domains" associated with old place names from my testing. I've deleted the place names in the https://dashboard.vircadia.com/places page but the domains still show with the deleted place names listed. The "delete" icon doesn't delete the domains.

**Comment by kasenvr** [comment]
Which one did you try to delete that did not work? I deleted a domain while in admin and one while not in admin and both worked.

**Comment by Misterblue** [comment]
does this now work?

**Comment by ctrlaltdavid** [comment]
No, it still doesn't work. I tried deleting each and every domain listed in my "Domains" page per the following screenshot. None were deleted.

![cannot-delete-domains](https://user-images.githubusercontent.com/7455448/94381043-62d75980-0194-11eb-9bf7-b79173bb388e.png)

Iamus Dashboard v0.0.1e
Metaverse version 2.2.7

Note: I don't know why a couple of the domains are showing a user count of 1. No domain servers were running (nor recently running).

**Comment by kasenvr** [comment]
Can you take a snapshot of your console output from when you tried to perform the action and when nothing happened?

**Comment by vegaslon** [comment]
code clearly checks for grid admin role before it deletes a domain. Iamus docs also state it only works for grid admins. So need a way that users can delete their domains.

**Comment by Misterblue** [comment]
I will add the domain account to the acceptable deleters.
