### ISSUE TITLE
Allow only one account per e-mail address?

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/Iamus#42]

**Comment by kasenvr** [comment]
One consideration for this will be that we will have to wipe all but the oldest account of an email address. Also, this will cause any domain ID's to be lost that are corresponding to it.

**Comment by JulianGro** [comment]
Would we?
We could just disallow new accounts from registering if the email address is already in use.

**Comment by kasenvr** [comment]
Well the problem is if we implement a recovery by email option, I imagine it would die if you tried to use it on an account with multiple usernames to an email. Now backwards compatible code can be added, however... that's a bit bothersome to manage that code for only a few accounts.

**Comment by Misterblue** [comment]
Allowing multiple accounts per email is a nice feature going in (creating test accounts, for instance) but it's a problem at the other end (how to recover accounts, ...).

I'm leaning toward making emails unique. Any strong counter arguements?

**Comment by JulianGro** [comment]
I would like unique emails just to help with banning people. Someone who wants multiple accounts probably also has multiple email addresses. Problem with multiple accounts per address would be that people can just make a new account when they get banned using the same email address. Of course you could still ban the email address, but then there is the problem with stuff like family accounts, where multiple different people might be registered with just one email address. Of course if you were to ban an email address that is used by multiple people, you would ban everyone when only one of them did something to get them banned.

**Comment by Misterblue** [comment]
Unique emails does sound better. I will add  that restriction.
