### ISSUE TITLE
Domains & Places generated on first run don't get associated with the user

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/Iamus#44]
It would seem that if you get a temporary place name (the domain-server will automatically do this on your first run) then once you connect the server with your account, the domain ID & the place name will not get associated to your account afterwards even though it should...?

One example of the potential issue in action as reported by user "Jaye".
```
Oct 10 10:57:53 v1 domain-server[2862]: [10/10 10:57:53] [CRITICAL] [default] PAGE: Public key upload failed from AccountManager to QUrl("https://metaverse.vircadia.com/live/api/v1/domains/13122642-4415-4087-a665-4b31eba1825f/public_key") "Host requires authentication"
```

**Comment by Misterblue** [comment]
After discussions, the "fix" for this is to not use the "--get-temp-name" feature of the domain-server and, instead, let the domain-server startup without any metaverse-server association. Then, when the domain server associates the account with the domain-server, at that time, get a name for the domain and register the domain and a place for that domain.
