### ISSUE TITLE
New session ID assigned to user every 5 seconds if logged in

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/Iamus#45]
2020.2.3
On a domain that allows anonymous connections
If logged in, the following message is reported in the program log every 5 seconds:
```
[DEBUG] [hifi.networking] Metaverse session ID changed to "d8f8d897-13d2-4352-8f3b-bb7fb0746042"
```

If not logged in, the problem does not occur.

**Comment by Misterblue** [comment]
I haven't been able to duplicate this with v2020.3.0-rc

**Comment by kasenvr** [comment]
What domains did you visit?

**Comment by Misterblue** [comment]
I visited metaverse.bluestuff.org. I have a freshly built ice-server, domain-server, and metaverse-server running in my test setup.
The code does look like, if the Interface is sending avatar heartbeats to the metaverse-server, that responds with the sessionID and this log message is output whenever the sessionID is set (happens every heartbeat).
The real question might be why Interface is trying to set it every 5 seconds. I remember seeing this before but never ran the problem down.
There is a problem here somewhere. Just haven't found the source.

**Comment by Misterblue** [comment]
After some more poking, looks like I can duplicate this. Interface sends an avatar heartbeat to the metaverse-server very 5 seconds. The heartbeat response returns the sessionID which DiscoverabilityManager sends to AccountManager who outputs the reported debug log message.
There must be a different heartbeat  code path for anonymous avatar as opposed to regular avatars.

**Comment by Misterblue** [comment]
I have applied a "fix" for this by returning the avatar's node_id as the session_id. Previously, Iamus was returning an ID generated for every new "session" which was each connection from a different IP/port. The domain-server seems to keep changing ports it uses to talk to the metaverser-server.

This is still returned with every heartbeat request but the value should not change any more.

**Comment by Misterblue** [comment]
with changes I've made, does anyone still see this problem?

**Comment by Misterblue** [comment]
Seems to be fixed. Reopen if the problem is noticed again.
