### ISSUE TITLE
Add 'User' stats to the stats API

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/Iamus#56]
Things like user counts and historical user counts would be very nice to have to display and show usage. There are probably more metrics that would be handy as well.

**Comment by Misterblue** [comment]
There are currently two categories:
os: cpuBusy, memUsage,
server: apiRequests, apiErrors

The plan is for a third category:
metaverse: totalUsers, totalAnonUsers, totalActiveDomains

Other metrics?

**Comment by kasenvr** [comment]
totalActivePlaces would be cool too. :) I find most often that a lot of the time there are many more people online in private worlds than people realize.

**Comment by Misterblue** [comment]
Was added in 2.2.21
