### ISSUE TITLE
user registration: "Badly formatted username" error when username exists

### ISSUE THREAD

**Issue by ChristophHaag** [kasenvr/Iamus#62]
https://github.com/kasenvr/Iamus/blob/729cdd156c95d514751a7663bafd6b584c725d49/src/Entities/AccountEntity.ts#L124 the username should still be considered valid if it already exists, it should be a different check and different error.

**Comment by Misterblue** [comment]
This is #48 which says the 'validate' operation should return why it failed. At the moment, the 'validate field contents' operation just returns a boolean but doesn't say why it failed. It needs to be re-worked to somehow return a message on why the field setting validation failed as the current system is not very user friendly -- "it didn't work" does not tell you what to fix.
I attempted to centralize field value checking. I need to snazzy that up a bit.
I will look to advancing this problem in the queue as new users are stumbling over its effects.

**Comment by Misterblue** [comment]
The validation code will now return an error and will return different errors for bad characters and already existing.
Fixed in Iamus 2.3.2
