### ISSUE TITLE
"Badly formatted email" error on valid mails

### ISSUE THREAD

**Issue by ChristophHaag** [kasenvr/Iamus#63]
Don't validate email addresses with a simple regex https://github.com/kasenvr/Iamus/blob/729cdd156c95d514751a7663bafd6b584c725d49/src/Entities/AccountEntity.ts#L143

Validate email by actually sending an email. See also  #47.

https://www.youtube.com/watch?v=xxX81WmXjPg

**Comment by Misterblue** [comment]
Which way should Vircadia go? I see three possible changes:
1) Completely RFC compliant regex (it's long -- I checked)
2) not testing at all (it's an email and if it doesn't work, that's the user's and admin's problem)
3) make the regex a server configuration parameter so a grid can be as picky as it wishes

Going for 2) and eventually having #47 operational (verify email operation) is the direction I'm leaning.
What is the opinion of the crowd?
