### ISSUE TITLE
Server Settings > Places table is empty

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/Iamus#7]
I don't have a place connected to my domain. But (according to my account dashboard) a temporary place has been associated with my domain - "cyan-condor". But the Settings > Places table is empty.
I would expect:
1) The temporary place to be listed in the table.
2) There be a row with a "+" sign to choose / create a place.

PR370 Places table ...
![empty-places-table](https://user-images.githubusercontent.com/7455448/93734307-dcb79200-fc2c-11ea-97e0-3d963c024dc4.png)

Expected Places table (from similar 2020.2.5 server setup) after clicking the "+" button ...
![expected-places-table](https://user-images.githubusercontent.com/7455448/93734317-e5a86380-fc2c-11ea-99dd-31ded26960a6.png)

**Comment by Misterblue** [comment]
Should be fixed in version 2.2.4
